"""
A two-level classic cache hierarchy with a configurable L2 replacement policy.

This is a modified copy of gem5s stdlib
``PrivateL1PrivateL2CacheHierarchy``
(``src/python/gem5/components/cachehierarchies/classic/private_l1_private_l2_cache_hierarchy.py``).
The stdlib version hard-codes the L2 associativity and gives no way to reach
the replacement policy from outside, which is the one knob this whole project
is about. Copying and editing it is a much smaller job than writing a
hierarchy from scratch.

What changed relative to the stdlib original:

1. ``l2_replacement_policy``, ``l2_assoc`` and ``l2_prefetcher`` are
   constructor parameters and are threaded through to the L2 cache object.
2. The L2 prefetcher defaults to off. The stdlib L2 attaches a
   ``StridePrefetcher``. Leaving it on would mean the miss counts we compare
   across policies also reflect prefetcher behaviour, which muddies exactly
   the measurement we care about.
3. The L1 data cache prefetcher is off too. An L1 prefetcher issues its own
   requests down to L2, so leaving it on would mean part of the L2 access
   stream we are measuring was generated by the prefetcher rather than by the
   benchmark.
4. Relative package imports became absolute ``gem5.*`` imports so the file
   works as a standalone config outside the stdlib package tree.

Everything else, including the port wiring, is the stdlib code unchanged.
"""

from typing import (
    Optional,
    Type,
)

from m5.objects import (
    BadAddr,
    BaseCPU,
    BasePrefetcher,
    BaseXBar,
    Cache,
    Clusivity,
    L2XBar,
    SystemXBar,
)
from m5.params import Port

from gem5.components.boards.abstract_board import AbstractBoard
from gem5.components.cachehierarchies.abstract_cache_hierarchy import (
    AbstractCacheHierarchy,
)
from gem5.components.cachehierarchies.abstract_two_level_cache_hierarchy import (
    AbstractTwoLevelCacheHierarchy,
)
from gem5.components.cachehierarchies.classic.abstract_classic_cache_hierarchy import (
    AbstractClassicCacheHierarchy,
)
from gem5.components.cachehierarchies.classic.caches.l1icache import L1ICache
from gem5.isas import ISA
from gem5.utils.override import *


class ConfigurableL2Cache(Cache):
    """
    The stdlib L2Cache with two additions: the replacement policy is a
    constructor parameter, and the prefetcher can be omitted entirely.
    """

    def __init__(
        self,
        size: str,
        replacement_policy,
        assoc: int = 16,
        tag_latency: int = 10,
        data_latency: int = 10,
        response_latency: int = 1,
        mshrs: int = 20,
        tgts_per_mshr: int = 12,
        writeback_clean: bool = False,
        clusivity: Clusivity = "mostly_incl",
        PrefetcherCls: Optional[Type[BasePrefetcher]] = None,
    ):
        super().__init__()
        self.size = size
        self.assoc = assoc
        self.tag_latency = tag_latency
        self.data_latency = data_latency
        self.response_latency = response_latency
        self.mshrs = mshrs
        self.tgts_per_mshr = tgts_per_mshr
        self.writeback_clean = writeback_clean
        self.clusivity = clusivity
        self.replacement_policy = replacement_policy
        if PrefetcherCls is not None:
            self.prefetcher = PrefetcherCls()


class NoPrefetchL1DCache(Cache):
    """
    The stdlib L1 data cache with the stride prefetcher omitted.

    The stdlib class always constructs a prefetcher, so there is no
    parameter that turns it off. Since prefetch requests reach L2 and
    would land in the numbers this project reports, the cleanest fix is a
    small standalone class that simply never creates one.
    """

    def __init__(
        self,
        size: str,
        assoc: int = 8,
        tag_latency: int = 1,
        data_latency: int = 1,
        response_latency: int = 1,
        mshrs: int = 16,
        tgts_per_mshr: int = 20,
        writeback_clean: bool = False,
    ):
        super().__init__()
        self.size = size
        self.assoc = assoc
        self.tag_latency = tag_latency
        self.data_latency = data_latency
        self.response_latency = response_latency
        self.mshrs = mshrs
        self.tgts_per_mshr = tgts_per_mshr
        self.writeback_clean = writeback_clean


class ConfigurableL2Hierarchy(
    AbstractClassicCacheHierarchy, AbstractTwoLevelCacheHierarchy
):
    """
    Private L1 instruction and data caches per core, plus a private L2 whose
    replacement policy, size and associativity are all configurable.

    The L2 is the last level in this hierarchy, so it is what the writeup
    calls the LLC.
    """

    def _get_default_membus(self) -> SystemXBar:
        membus = SystemXBar(width=64)
        membus.badaddr_responder = BadAddr()
        membus.default = membus.badaddr_responder.pio
        return membus

    def __init__(
        self,
        l1d_size: str,
        l1i_size: str,
        l2_size: str,
        l2_replacement_policy,
        l2_assoc: int = 16,
        l2_prefetcher: Optional[Type[BasePrefetcher]] = None,
        membus: Optional[BaseXBar] = None,
    ) -> None:
        AbstractClassicCacheHierarchy.__init__(self=self)
        AbstractTwoLevelCacheHierarchy.__init__(
            self,
            l1i_size=l1i_size,
            l1i_assoc=8,
            l1d_size=l1d_size,
            l1d_assoc=8,
            l2_size=l2_size,
            l2_assoc=l2_assoc,
        )

        self._l2_replacement_policy = l2_replacement_policy
        self._l2_prefetcher = l2_prefetcher
        self.membus = membus if membus else self._get_default_membus()

    @overrides(AbstractClassicCacheHierarchy)
    def get_mem_side_port(self) -> Port:
        return self.membus.mem_side_ports

    @overrides(AbstractClassicCacheHierarchy)
    def get_cpu_side_port(self) -> Port:
        return self.membus.cpu_side_ports

    @overrides(AbstractCacheHierarchy)
    def incorporate_cache(self, board: AbstractBoard) -> None:
        board.connect_system_port(self.membus.cpu_side_ports)

        for _, port in board.get_mem_ports():
            self.membus.mem_side_ports = port

        self.l2buses = [
            L2XBar() for i in range(board.get_processor().get_num_cores())
        ]

        for i, cpu in enumerate(board.get_processor().get_cores()):
            l2_node = self.add_root_child(
                f"l2-cache-{i}",
                ConfigurableL2Cache(
                    size=self._l2_size,
                    assoc=self._l2_assoc,
                    replacement_policy=self._l2_replacement_policy,
                    PrefetcherCls=self._l2_prefetcher,
                ),
            )
            l1i_node = l2_node.add_child(
                f"l1i-cache-{i}", L1ICache(size=self._l1i_size)
            )
            l1d_node = l2_node.add_child(
                f"l1d-cache-{i}", NoPrefetchL1DCache(size=self._l1d_size)
            )

            self.l2buses[i].mem_side_ports = l2_node.cache.cpu_side
            self.membus.cpu_side_ports = l2_node.cache.mem_side

            l1i_node.cache.mem_side = self.l2buses[i].cpu_side_ports
            l1d_node.cache.mem_side = self.l2buses[i].cpu_side_ports

            cpu.connect_icache(l1i_node.cache.cpu_side)
            cpu.connect_dcache(l1d_node.cache.cpu_side)

            self._connect_table_walker(i, cpu)

            if board.get_processor().get_isa() == ISA.X86:
                int_req_port = self.membus.mem_side_ports
                int_resp_port = self.membus.cpu_side_ports
                cpu.connect_interrupt(int_req_port, int_resp_port)
            else:
                cpu.connect_interrupt()

        if board.has_coherent_io():
            self._setup_io_cache(board)

    def _connect_table_walker(self, cpu_id: int, cpu: BaseCPU) -> None:
        cpu.connect_walker_ports(
            self.l2buses[cpu_id].cpu_side_ports,
            self.l2buses[cpu_id].cpu_side_ports,
        )

    def _setup_io_cache(self, board: AbstractBoard) -> None:
        """Create a cache for coherent I/O connections"""
        self.iocache = Cache(
            assoc=8,
            tag_latency=50,
            data_latency=50,
            response_latency=50,
            mshrs=20,
            size="1KiB",
            tgts_per_mshr=12,
            addr_ranges=board.mem_ranges,
        )
        self.iocache.mem_side = self.membus.cpu_side_ports
        self.iocache.cpu_side = board.get_mem_side_coherent_io_port()
